//! Raw bindings generated by rust-bindgen. Only use this if you know what you're doing!

#![allow(warnings)]

// mod internal {
//     include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
// }

// pub use internal::root::*;
mod bindings;
pub use bindings::root::*;
