//! Raw bindings generated by rust-bindgen. Only use this if you know what you're doing!

#![allow(warnings)]

mod internal {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use internal::root::*;

impl Default for dmVMath::Vector3 {
    fn default() -> Self {
        unsafe { std::mem::zeroed() }
    }
}

impl Default for dmVMath::Point3 {
    fn default() -> Self {
        unsafe { std::mem::zeroed() }
    }
}
